swagger: '2.0'
info:
  title: 越动嵊州城接口
  description: 越动嵊州城接口文档
  version: 1.0.0
host: 127.0.0.1
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /index/login:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 登录注册
      description: 1.1登录
      parameters:
        - name: username
          in: formData
          description: 用户名
          required: true
          type: string
        - name: password
          in: formData
          description: 密码
          required: true
          type: string
      responses:
        '200':
          description: 成功返回1，否则0
          schema:
            $ref: '#/definitions/login'
  /index/register:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 登录注册
      description: 1.2注册
      parameters:
        - name: email
          in: formData
          description: 邮箱
          required: true
          type: string
        - name: username
          in: formData
          description: 用户名
          required: true
          type: string
        - name: password
          in: formData
          description: 密码
          required: true
          type: string
      responses:
        '200':
          description: 注册结果
          schema:
            $ref: '#/definitions/common'
  /index/modifypwd:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 登录注册
      description: 1.3修改密码
      parameters:
        - name: oldpassword
          in: formData
          description: 旧密码
          required: true
          type: string
        - name: newpassword
          in: formData
          description: 新密码
          required: true
          type: string
      responses:
        '200':
          description: 修改结果
          schema:
            $ref: '#/definitions/common'
  /home/headlines:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 首页
      description: 2.1 轮播图
      parameters:
        - name: status
          in: formData
          description: 头条状态（1为可用，0不可用）
          required: false
          type: integer
      responses:
        '200':
          description: 轮播图返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/headlines'
  /home/famous:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 首页
      description: 2.2 越剧名家
      parameters:
        - name: kind
          in: formData
          description: 越剧博物馆类型（1 越剧名家；2 越剧流派；3 经典剧目；4 经典人物；。。。）
          required: false
          type: integer
      responses:
        '200':
          description: 越剧博物馆返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/famous'
  /home/troupe:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 首页
      description: 2.3 越剧团
      parameters:
        - name: kind
          in: formData
          description: 越剧博物馆类型（1 越剧名家；2 越剧流派；3 经典剧目；4 经典人物；。。。）
          required: false
          type: integer
      responses:
        '200':
          description: 越剧博物馆返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/troupe'
  /home/news:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 首页
      description: 2.4 最新资讯
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/news'
  /news/showall:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 资讯
      description: 3.1 所有资讯
      parameters:
        - name: pagesize
          in: formData
          description: 分页每页几条数据  默认6
          required: false
          type: integer
        - name: pn
          in: formData
          description: 分页第几页  默认1
          required: false
          type: integer
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/news'
  /news/selectone:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 资讯
      description: 3.2 某个资讯内容
      parameters:
        - name: id
          in: formData
          description: 资讯id
          required: true
          type: integer
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/onenews'
  /museum/showkind:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 越剧博物馆
      description: 4.1 越剧博物馆各个种类内容
      parameters:
        - name: kind
          in: formData
          description: 越剧博物馆的种类（1越剧名家；2戏服展示；3道具百科；4经典人物；5经典剧目；6越剧艺术团；7剧照）
          required: true
          type: integer
        - name: pagesize
          in: formData
          description: 分页每页几条数据  默认6
          required: false
          type: integer
        - name: pn
          in: formData
          description: 分页第几页  默认1
          required: false
          type: integer
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/museum'
  /museum/showclass:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 越剧博物馆
      description: 4.2 越剧博物馆所有种类
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/class'
  /museum/selectone:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - 越剧博物馆
      description: 4.3 某个越剧博物馆内容
      parameters:
        - name: id
          in: formData
          description: 越剧博物馆id
          required: true
          type: integer
      responses:
        '200':
          description: 返回数据
          schema:
            type: array
            items:
              $ref: '#/definitions/onemuseum'
definitions:
  common:
    type: object
    description: 通用格式
    properties:
      code:
        type: integer
        description: 0=成功 1=失败
      msg:
        type: string
        description: 失败信息
      data:
        type: object
        description: '成功数据 单对象空{} 多对象空[]'
  login:
    type: object
    description: 登录返还参数
    properties:
      code:
        type: integer
        description: 1=成功 0=失败
      msg:
        type: string
        description: 失败信息
      data:
        type: object
        description: 登录接口返回参数
        properties:
          sessionid:
            description: 标识id
            type: string
  famous:
    type: object
    description: '返回4条越剧名家的json数据,也可以在famous集合中取'
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 名家姓名
        type: string
      remake:
        description: 备注  简介
        type: string
      id:
        description: 主键id
        type: integer
      kind:
        description: 类别id
        type: integer
  headlines:
    type: object
    description: 返回状态为1的轮播图数据存在headlines集合里，同时传回json数据
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 头条标题
        type: string
      introduction:
        description: 头条简介
        type: string
  troupe:
    type: object
    description: 返回5条越剧团数据存在troupe集合里，同时传回json数据
    properties:
      picture:
        description: 图片路径
        type: string
      troupeName:
        description: 剧团名
        type: string
      remake:
        description: 备注  简介
        type: string
      id:
        description: 主键id
        type: integer
      kind:
        description: 类别id
        type: integer
  news:
    type: object
    description: 返回4条已经发布的最新的资讯数据存在news集合里，同时传回json数据
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 标题
        type: string
      publishTime:
        description: 发布时间
        type: string
      author:
        description: 发布人或来源
        type: string
      clickNum:
        description: 点击量
        type: integer
      remake:
        description: 简介
        type: string
      isHot:
        description: 是否热门
        type: integer
      id:
        description: 主键id
        type: integer
  onenews:
    type: object
    description: 返回某个资讯json数据
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 标题
        type: string
      publishTime:
        description: 发布时间
        type: string
      author:
        description: 发布人或来源
        type: string
      content:
        description: 资讯内容
        type: string
      isHot:
        description: 是否热门
        type: integer
      clickNum:
        description: 点击量
        type: integer
  museum:
    type: object
    description: 以json形式返回越剧博物馆数据
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 标题|剧团名|名字
        type: string
      source:
        description: 发布人或来源
        type: string
      remark:
        description: 简介
        type: string
      kind:
        description: 种类
        type: integer
      id:
        description: 主键id
        type: integer
  onemuseum:
    type: object
    description: 以json形式返回越剧博物馆数据
    properties:
      picture:
        description: 图片路径
        type: string
      title:
        description: 标题|剧团名|名字
        type: string
      source:
        description: 发布人或来源
        type: string
      content:
        description: 内容
        type: string
  class:
    type: object
    description: 以json形式返回越剧博物馆所有分类
    properties:
      kind:
        description: 种类编号
        type: integer
      name:
        description: 种类名称
        type: string
      url:
        description: 路径
        type: string
